steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - BASE_IMAGE=${_REGISTRY}/jupyterhub-k8s-singleuser-sample:4.2.0
      - --build-arg
      - IMAGE_VERSION=4.2.0-r3
      - -t
      - ${_REGISTRY}/jupyterhub-k8s-singleuser-standard:4.2.0-r3
      - jupyter-singleuser-standard

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGISTRY}/jupyterhub-k8s-singleuser-standard:4.2.0-r3

images:
  - ${_REGISTRY}/jupyterhub-k8s-singleuser-standard:4.2.0-r3

serviceAccount: projects/gcp-sbx-edp-gke01/serviceAccounts/sa-sbx-build@gcp-sbx-edp-gke01.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
